apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spec.name }}-deployment
  labels:
    app: {{ .Values.spec.name }}
  namespace: {{ .Values.spec.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.spec.name}}
  template:
    metadata:
      labels:
        app: {{.Values.spec.name}}
    spec:
      containers:
      - name:  {{.Values.spec.name}}
        image: ghcr.io/ravelin/goapp:0.0.5
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
